version: "3"
services:
    nginx:
        build:
            context: ..
            dockerfile: docker/Dockerfile.nginx
        image: kangaroux/jessie.moe:nginx
        ports:
            - 80:80
            - 443:443
        restart: on-failure

        # Uncomment for SSL
        # volumes:
        #     - LETS_ENCRYPT_DIR:/usr/share/letsencrypt/:ro